version: "3"

services:
    db:
        image: mysql:8.0.23
        #platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3308:3306
        networks:
            - logparser
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - log_parser_app_sync:/var/www/symfony/
        networks:
            - logparser
    nginx:
        build:
            context: ./nginx
        volumes:
            - log_parser_app_sync:/var/www/symfony/
        ports:
            - 8080:80
        networks:
            - logparser
        env_file:
            - .env.nginx.local

volumes:
    log_parser_app_sync:
        external: true
    db_app:

networks:
    logparser:
